apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 21.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: ccm-hcloud
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/ccm-hcloud
      targetRevision: 21.0.0
      helm:
        valueFiles:
          - $values/k8s/vpn-obmondo-com/argocd-apps/values-ccm-hcloud.yaml
    - repoURL: https://github.com/nihaldivyam/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
