apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 16.0.1
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cluster-api-operator
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-api-operator
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/cluster-api-operator
      targetRevision: 16.0.1
      helm:
        valueFiles:
          - $values/k8s/vpn-obmondo-com/argocd-apps/values-cluster-api-operator.yaml
    - repoURL: https://github.com/nihaldivyam/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
