---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAKoAZKDbDoU6utf/dtIoTaJdfxumECVsG9v14XW+C1dAn3uNdv47zIdaRiHkoxHQlguL2TRl67J3Xd1+ZV2qcKOgaEuHviUmsejIkoLaMhr+LcGybdH+XARc1Re7XiWYEcqhOf0lhm9juGvhp0/jgK18wHgIOpYTDoIyqTJ/DRO5CxYfmXQcARyPSduf/plxGeu1b/yhvF6GZLVJuO1csxwJ+/ja7hG31Pg5JqAWpuf8QqWf6e6RR9P4AXc8kodmsGmqXNA83rYohhy6HHVFB5ao/U/WMUpbLnvxs/AbHv6Aob3/WGmmNtXneu0LZWC5UdyhDgiav7TSW/em5DFERfeIzPsskP0Aq2O2ZGUjzyJD0r8CfOYs3XDLpOSfVHHr0vJjuqSLwq0wou4cllADrvvtYxMhPI8MjCfBLI58jLCv7FOjn6mf+i5MoukvB9DFARkh1oWVRkC7szAXnZgA/Jzztqxaxl4w1vuuToKY5jyMX7gNbeyS9Kt3zRJ5ShL+kLvboCugwSOZKgYckNYldIUZLhMXqzRHw53mXPeZEa1NxlFsy1i5YZce7dziIz8KtU7wqSUa4V/v37XlEYw966p1V8+4z2LHLmeyyyt64UF39hJoziy1mQXv8AJ9J6fGQTk+++wqRnA3RbgBD6QKe2w+aGult65m1hCNuHu9JSTxp+MDfeKUkhV5uvYeLeL+GBgi+1lLh/vOHo/WK9HBzsgI8BPI5dyFMQqAM8OiAESjJRdrlXWgh7C9iV28151inh7WbNxz/XzDlCaC9/vWSt
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
