---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCA/aAibUc47B/9KmqEaGSrlkWubx21vMot5Ach4iKH3UbC8RuZDUwB5HCI6ZjDUOSoEEP4/m+CZlcnWIITLkKrRVtfUcaDC1Fr0yuhI532BUGMRn5PsDTdzWyxItNXs1uk0IbhhfagPsctAZUKuy879jv8hBJGcsb2QWGFRuaqPAqmD1jzZljGZtO5ISJkuu4YokGIsP65dW+5xlUFva9eG4jfU4MKQEnVp0+3QVhhjQUb41pGI82qO5j+TGsbsUA8sOkybbCcBSh8V+gvnYVH9sT5wGoRpj0V/VzfgzQZJNbL0O9OmElDfrdssVAa9J7NHHwIWXpjMPlcvYFwqXGiKSSj1EW5DNzUvjOrNN0enL1mqw8CBAoqWjWvLFtVK0P7dCVy62G43gvc3MJM8xJdo99a2a+V246np2msgAhVICox74eJsRL+JdUWmSpUo2FRpIfeYFNM6/VZAt56gmdSiABkpIsMF+AcAspgQTDoEkP8aBCQeWxIhogYU3fQf2ULeDwJLQ2uc/yuiybrRUbITdtycXRp2sXpUei2f8yJjTP7TQwMekur/RWV7+TbKb+B9eCDMe0dK5BQDtmKlrRU6ixPAYyZMD7d4z9iq5rNr66Y4hF8cZB6a1WxQSuVi1uPPVGC1ZewJkSyIBp0yhRlgNa1/iMQMjXSIY83HfzzKsS1nCHn9z5BQANvETvuISnyAgI19frkmmawDhVJXLy71pNlBU09KgdWcJapoVqsrlBKhokVRDIw7qxbbRze4FR/VeSGpgAPYPffTYYQWCPz
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
