---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBXkhW2k/GfRhuk3faW+WJUX7XUCabA2ZZqT9oSTYiDXazJVIG0lhuNdrjwLlPJKwaZoFsJtfMYqsaGcdji1AS0geHiv+1rB1I8vTbKdtYz6IOQJ8rDnrL9gxXi7fGjXQUhjNyo7tr3+N7qQfYvkSl7/HzIboQVIDjAiDPyF2maUOor8J1trWZJrDiiHA6biQ/nDJPGaZktZQi9ZuMXJ84LOWLDvWUasTRv8DGWFrrbMPNrnvPXdpkNY2G16pvELCwzL7B5fnCSrqW7mq+D8ubsSoovCI4k/IHnuMQ/UWyTcsRYZjyx2I+6q1SzWZpbS97lJHTYmKYiJaxIk8YMwjh3NON9l2iAU46eF+Z/jNcsPFny+uB9QP6m9iH2EJunxKyz7zMSi+Jt0Q3BeXDed50/O1OoeArcz6TdbVz6tRd/kbyucoBGDZ2eE6DO10kpvxfeDVDxmm64hntZE8TYPzh2oBKw9P8j90Ak5QtNfTdoyDkhdi0M3wt02zJPDIh8jrsuo5wwOKWBRSo6PTMpTlWkZ1DokSGSXtp+7SKMtkzKBen0Nb9l77shhlWpk5bQCu5T3NwcBIN7fbm05eS4aAXbZbVa+QkBXJQevmgI358qVp3O0kFTHn5RCEC5dhv0tqTBqqaxQue0qJAbaRqWcimmYkNulyMrEBBsV0k8F6I54o52UGJ08kJxJW4i9NqZIzohBu87++XtOWVtGd/UrBnRsMBrFmpPf+Byi59fKyT8FBrK7bpMzvZdeMTMImQF8tW2PFa8Jxrs3abRs8exN8v3
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
