---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAO1n1zxOG0GYSdFCYW7I9kHD1F2wiiJY+a+9sT5JQSDR6yoZZMwcOlosbviBeRgilp5Uzn/Mb5bob68fDnJ89qdwX3r/y9cFGlSUGrADGmRVswVCrLamJF6hrALbfSOKQ3JwqKs4wEJUnVu5sG0iQjI7ctDc+RqxqaeJJyN/6mjs5r4EPNRU2GKNZFILkJGYy52S6RDnvMceQ7BnL4hV5CUtQvH6rKvt9mRHYe7HoHupr8X4xvHAHcw6rafI1bycP3XF8dVwbiJDxzaudsTVBoN3erVBsb4V6Gh+YSgf7F4MTWqNB7h8lqNWNo1W+fNHsx+Fv+X2qCjA0kT22WueZLBmiBwpPxI5FB23qJnQH5Hg9UD9WAc4SojTuKW43OHHGiiDRq224SfJtWSEO2l1Qei5kA0oWGGJx46BtW+c4QVVhnV2kE3Y3rb4N+50S3j/6xgB7SeCN/WwH9fQOb5yV8uUrGDbslADUhS5uIQhI5dchLgzgNeBkpihYHoUjG55nrzoIyXlFIyirUB7DwAFSWutg0g5ti9MPXFiPPnianqPZEeGigzJ68lx7dtlvpF7SGI8G3Z9bg7mlp6LTrshyo7xQUeosZG7WKe8zENmaELcHY+FTdCRB1eZwBAYMsAdvOvqoXjw/Gc1tZm5bHrCQ26R7sNF4Fz9haKb/hrl/PSO9ln9Irr4u2Zu+aw9fzDQKveFgnZKZksBiDsfctyjYL0Hd6WeO9Z4cdJFCLLGft5uNDC/bRiY2aWPqZxUJ5vXbB62b7vHgUZugd4NE0Zsbp
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
