---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBkNDWhySihaDPQp/HtQGCEl7MnDwy812VYNHvrvumJNWfNDF83CAkPULrvhkr5OZ7Ct0Q5WXRagOP2CF3MkBSp6pHldgOsTVLHQY2TwFK20+XFblin2f8zYezIXC6RDRsG4taV6n5yeZ/PDbzA1y3+5opq/6AW3/b/qc3ZzyEgNONw61iQiECdc2L4BjRMOiEomZMFC5FjWWbt1J/17Kl4vZF53vL2ngCIkNzmiJKN5v8iz9msL5C2INBGNMhrXW7l+XmcTxVgmN7vPgOiwkOkR7kaD5VjaJX1p/Xyb2eI6ZKfoJqh9si53Y0Y6nsQLWBpQhLCVw0oSPrL1cNGT0HWef4NyXM25ZTLmogEThpseyUVWOY8GbHrU40JT01AAKRC8XCkzNcIQjaJZQ8SgvLpQktMn6KoxO1WBuUqfDHJveVRogBol5USRaOKI851QqdSzAQBuyAHc0HnsRiZUMkbk51P/T5KIymLPWF1Cd0EEvIR02ab/MGbrbYH+Pt0vUEgRRbVqTuMcEhrUol1hWq/IBypdz0mZbQ9VmzV8j9Se3gwmXBw9BkX1/YJa7MCuN8KRV/K9f+I9ptP2DV363oPCOkGgvb5GzoKWSFQ09wU7htX4fnD4j3aPYBKPRAcHD/H2e8N4mJCY01S7+tgLJGvvi0fVT+9ZCGZQNdCkg9oWHlBCiw8exnFi1tS+IXGIYK4r9W1HEi2I7/TbX2j+RGdHNVLeZMVIw12a6we7VHwS68Ld4st1CLLDR7fzzUY+vHH2LjQUEWbBEju79zE+rRg
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
