---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCKYuL5P/u4ncpTwrbCwMAXKdY6AnxWVJFT//BPdZdHhJ/RkL5EiPX/+7FQD9GNSPoLyqwu86CCBJTuODkZUXtBBSq5LwXwaKM4EAEiVscIglpB9Qze6O1ji5zm+NsjSbLJhEyIESIJPdHJ15d1R+ltImHDbVZ713noH7DV5l5niKI3/CmOPC633N3lJVnDA6ykDEoLN3WyZ3/Ra+NMiD8lCCEaHOOTI1e1pAyx+mw+zhyjor2p5IfwXXGhbNl5ZBgRdMv8quX9SoGoyizjK4/1n6t72jWFA/5YfUjzb51JjBohJtupQ8Z6h5aVkzu/Ixfbb4X20IIQB7Cn4qvDd1yW9RyatUWvC7wDfiSuCpYkE2nYYgz+xJsdsWuHHlaTOTmQXcDhA+M872vGUS5MNRul61VK9HQbpIWmyPjmH7XCIkm3KhTyu51/SH9sTefqDavP7c/5KR/eVH1jhuS/euiuOe2lZrXBIAM0vsU1Cl8HdVwBimzWRfbbHpWM+27kDx7cW8Ju7aDNJ6dpe9ZF4gKQBK4bi8NGD0mSQhet7BilX4iWBq3vIa6FhhQZyQCZ34BYmcx9w0nVkOQHjCpWzjq0CcvqdPC+ysR2ieS4Qez0GZRVnyQDLhNOuUBZWrMj1KggCkPWSUXXxsQVF/qItON3Hh8rs0AqGeH9aA7thexTUeaxK3OyaL8Eb7hHwbpI8AkveQng5NYypIclL2JHEzUN+v8rx3SSFwqUG/zuEOUI4RyoeQ9FKCzZW1MK1brWsLaGAxz3ncGvLJolPF2tiMFe
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
