---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBFSWpnZmjOCR7psG9l6GhQ71kE0VlN+sB7A2MXc6eBGBD6gOAmayMzFFK299kOUMvgLdcsklkAjC8g1Gqw6a3WXckbA6Z6jaRpJ0UwJKQl7cLc6UnuoB7Z99MsihFMqWF2FqM48ErLadkVo39Vx7JKwm0uQnRfaSX12h9Db64wWvfxt1v4BtXn5OdoMvqN+eIVuRkfj1v1f/u5kIIWMxPly4/CeGn+FM1iaEg24muT6Y2y8Y4+U72iMWO92PUw3+HoJYbrF9Y7r/eRCTrsgPX9TjGfe4ATjrmm7rhHrPHTmlfEQM0ultVqlhkjLnQe+G1CDv7j7CNsMn2AMnwo8GdRmDqmGe69N7HJOMRLe9hNO8TAyVGl/FNY5YLdX/WB5sm4/yWTa4he2aBWr6Xn5+9/URO1sBfCZGrZD5/AsXi8/9WO3myBVwMPGs4OBiiNJGf4z5MZpAeW0sltZaAnOoymvC8RtBfqXkO3I6KhMBH/Q/xM6auVUDyifLx/UsqRhUnKBlqAvPv1qCIp9IPj3bGsGypEGkJbqDxU6YirMcmHtnrS7F56vXKVa606l79TV8kvP3lPv9unA5k/F0cjwUeXvcqhqln8Bvnz+iWBkEmtksPovah0aa1IPCaBzZO2z3MurIzApioUeYOzYjlG9K90cZrT2fjATXh/QLvwAlj9maGDYCnSYNc80+XCYcBWNrRzfE/MV50FxFaWEfpP9chTa3tUogULzaHyrX4lsnHFYUF49AWseHWFs5enpN26pAbRYI8OWqSwSOA6S+1piQmD
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
