---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgClGpRSXcNVOL4ajqr9FC4q0RzZcx6uZlC8uxEaTMsLBf5Edlcz4VsP/JcTRIzYoT7dfTHMRpB24LG7Z/U3n93y3I81dFo0mOmHlt0xEluHrqVErVRFUAI7H+BIoldGKwnQD/D2s/qvh7HKG4jSw/kkZ3bfuipqQ/Yeaoc6B5MLwNfHZikdXUsTRsXpjJpCcu1f1SSQdg26JjyMM2qCcqBmD3NW0eGRgP4qFFUjHWVKxaNxWM/xnnzG/5riEWkSjVB+6fqmCGH48j4AFx09CSBobjRWODIzjCEdAiFmdyHa6U6eyeMWHvCUWmLy4YVk/DtERlO79N2iaNAoc31egIOAUV18UL3/uctyTMgTDKQH95bVAPidLEqh0e367twPfVS2hZ51DPmwmKXzXB6lSxyeVCDDUtj5f12EjnAiKDJVtwl+Y307DvLGy6fc/9E0KS/9P1sQBtYWW6DSJMRF1SREMAJVTLs+JLhHG36MUjFSr07HTUv5x+U7O+UP4Y+AppTks8TJQ0KiJyY5KPqMZC3/cTMsXfY7aBDlNzq0NVsv9ZpQcLd/dYKiMWVJJ4ZbONhjZ6D7NHZp6B6k2QqucrbbMoLi9CCLH+4eb6mjNu9vPmE1N33TB1ssGgrBEALYc0LR4NT9UTmVp4CHw4APB2/RPaiElOYwuuRzO1SB8+AAiKbnELII9JeWgJ7IPqHTeFmmiL/fE3g5JAvOGH7z9mgn47x5OJ3ji9l70QeAzMmtUb9oVdMFoDcRQQj3OySHzsJJ5fBh7B6ACFvKJDfqjaiT
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
