---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCGuExoaRNhpycA9EoOWjgZ+ZXGd4SGryM+/KGBTKDTSVMPVYHyHaDbhSVWbS957WKKdKzgviUZE9nDURTrFpXq+43967VGKa6QQRuvUL9Pxb20y6KpnwlJl0n0lwJSjWfcq7ecdE4t3jqId7iG6jWbfLikF5hwrfGe6o4vFcOxJ/wrq7TOWHmFy59Di5PwxBooiF+pkHkmOhVPu7zR3NmnqDrJRxTvUr3ja4OHrENRuynnozY0oD0SSHFOCZ5B116SIw/pDY+1YIb2q+XPsgztjRCAXRZV7k61cDbUEzwVh+QlF9/RG89s1iVbkIBQJ6zjvlw2Rkw5yuruddpufK+Y8HJ+fsoRd+uvJbsXEIBGZ+tiKALEbp4A0YIGm4i8OStvOeppsev4yPGjKXg/svkJ0fB9HTse1l4aY02uwUzPk5aQXTDhLIcga50DamP88Jld9yiyBo1SW+8G6PUyDc1gzlBxZhkHuJjF377HwJnehjHa87DJgs52JKK1/00scmrWDRiL9Ut0YzzuxAfKsagI4auqSO+nattcJdGLo2DzaAXCC84K5/n2vhlsyLDeRjRreZiUwM7nOqU/Ly5mwr3x2TutbA1UpwXUsNA7/mYU/2F22lUAqnVOjU+9F/RuEOLWq3gwFo7piDeW9Cw7T4xiVkQeHekNbs4X9TWqdfwJZeZxSI4tZXWPpDLTogV4yaJMCKKWS8wA7YELQdu9W6Cb4UOQr91qMrkiXrSRL1dT7/pCWHcJyj8HkfLY06sYW3YNrV9VnV3ROT3+s4jv3nrc
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
