---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB5WiB+c84M8UBVtceoGa5ZHJWCAtMUtljkxgSQPJVkdyJYfjlJYzI1tB/+zBQfk3VhoeOd3w5jPlPXyxvEe768mrSkTJXMHm1LnmtvuiBtRYazEPYUoFi3t+IhUhJ990cNTCunw7qjury6EKjDH8dJBYPIursnmG1+638TJUHbJ6jdRsq0SRl0OoJp1f8nKMexRQz6BzXvnxMuhPXiHK9eyVzXJSp9V0Z/PUduo2e/8FP/k2KqZJkM0PL8QRube8gfBXp2Awyw7ipuU/KWjQMXD/4dTP/MuO0TRlx75pTMDCBthcLb4MMGr4LkWhRn4oUPGpkaHCIzk5QnZ4+HeSz9LA1Nwm3F7zlvRy8hNq742+0fzEz+7iSPw7lBmAn8LyxKSUtbXB47K+QyLN1KCZy6t0JNq69+WFm0M8jLCOwwvZ5mkZr9W8WntW8ifysdd2NVvD5COyvqQJd2hi+0Mdd1KlWyKyK/RxkywYTtkOneKAjW/mCnjVM0Ozu43tVwl8Cu7KmnL1/4VFe0c2wRY2lzEUwwimafn2sobOGlUVlHk4Hz6EHvqpQFKEAWk1FbPsEY/nIybKbx2Rz47+32q+uUdWLJkjjUtrvs2PRw273Gi1MSslQoMU4AUH+miL3etLqJ7KR7L9AG93AblExBVfKqBcJ12BsHkUu/Q3KBwngDVGm5cxVND8jX0s2jJrqSnanBNkyLms8julEpeI0DHfzCKwVxHhsxDTSnkSHCRQbFqZ5IqOfymHXReLHx4UgLXvPxIiS10U48UQLbcUBrd0Ti
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
