---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAqWca9i4Bt5a/aqvmpDOhxWUzjhxuqbqJEh4kkrU0Mxs5MaEHs/WSBXXWxzGVG2TcMUXoRWk3gXnBD2psUUpvdg1HAvoyr+jUjpmLc72mucmCiD4mbi15d+uLxtITeoYXnhoFHaaAgmsUVYaKJQ6sc898vVRA0hPEacA985kigHctjAANiUXa/mhnj89Zu6M4dnq7j0uK0veKWPjnJ7rEt+dnpGebM2jFwi3PVQllSlywnKOH+k/oaHtAvuD2vEzt0QbShNukmHbIHuV/mljTsJvVHQpnS0CQt8I6rbyR4tBhdp0hD6X3Er+rCXXeJNQkS7WxbN9TQE7HYKKRhyO92fGoU8oAm6eB32tCiuv29DCWSyCBLQjO+oKSMJHv4KLaDb1dqSeEFhNO37bdCUKa/XFhlOyqNAHMmzxGmrujEGLmyUZb43ehSvHfULdjf94bhSl1pzbaJw4tL4eZnY3cjPFL+mGfusETNkaq8HrENB0BKnPqty39OA5H8h81lHlA09e5bqztOlhjqB4d37rlkIz07NlvepZNzXX504Y74D+4vMBwmRBrjUOFkl9VebcnFjxeOZCuAaaDv+uUL+mon/8N6Y4XZ4BG59CQ8z68f3Cd3tyBniI0e9wAcR8DDMHpOtV7zo0qdkQKj3hAMxVZpYUruezXLTlTrLAwySiqePECZncU8Rmu1XHqxtd+K8EaJ7Iju0C1fM406gG8U4d0X/pTxNJstWKXEbr6kVkoAZe+T21pgw/Nevkr7UfEAlexca2jFIouRzUn9Wi/VmwGf
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
