---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB5WvbfiUdL67+OjNmcoeFHf1vRM3np1PMjL6WLqbeRVvRCspRhPA5gd4KcEuFLVExzyLoGe3rK8qytJwkGX4Q4ALNbYb21vjYymHjoqvzRk4PodjgOxf6JXzbUMEvnnFcaTWIuQty5VQr+CS8ADGdB7XDzM1kSX9mWbrOPAuws6EHXU9s/4o+uIwf2Gflk+SuhtF0Ig9nUoMJODSggEq3LcNqUP3MvXYjOtwsxs4ZeF5YnjvcgdPI/+47W5LLMdDjZjR0EJrrdZFj1qXsfvwxY8xAFNU9lr3ORQpj9FqzBKID7cUqdeQdCQXlEhfl9azzPMuZJeFFpdYLr0HlqfuQXxI3/PVBa0FOBK3RD1HNKmqcUQBtxrsJ3PzUbbXVs26+IWyXOgXxC7l0O75auH2bKv31LyTdYzFu1wGlDCpPD2uhjXMcRBefLwryX1foJ7IJR4kEiF00eAEvrpuTk9cErF+cs8Z5Uwxj5ypY3n0Zfiq8YFTPVc8x6KzN/DaNNDF5GBjy0GnWIaW6bt8ZAPKQXfCwXYeXQv1giKkYQms0ezFzuqn4buzfWAK1nQI6dd2tXLgHpJiWZ7u55mBlccBqf7CckIBju85GIyXXdFtv/XewULZXk8seMMryBwDSB5ug+y4ExRT6nFZZedogB4GEdPeID/1mwROZahLjXZ0qauWIA3NXQ+1jczDwXpd2DOh7Xjvjq61Kf8fOHypl+7M9cx0LQx2/XO3dAw92xDJBnrDaPrG/JN0bYIeDAGel7uF02P3UH1dDLL8kT2Vxcc6bc
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
